Fix for this branch - content-provider-investigation
The manifest file has been moved to the correct place.

Seems to be an AGP issue:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
```